### ISSUE TITLE
get_input vs raw_input

### ISSUE THREAD

**Issue by madduri** [fair-research/concierge-cli#3]
raw_input worked for me on python 2.7 in globus_login to get auth_code

**Comment by NickolausDS** [comment]
Oh I see. In your original error, I thought this was related to the browser instead of the input function. I tried on python2.7 and it popped right up. 

`get_input` was supposed to set the correct input function on either python2 or python3. Instead of explicitly juggling functions I think it will be better to pull from `six.moves.input`.

**Comment by NickolausDS** [comment]
I'll leave this open a day or so for any future comments before merging.

**Comment by NickolausDS** [comment]
This should have been merged a while ago, merged now.
